package com.zcb.projectmt.dao;

import com.zcb.projectmt.domain.ErrorCode;
import com.zcb.projectmt.domain.ErrorCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface ErrorCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    long countByExample(ErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    int deleteByExample(ErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    int insert(ErrorCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    int insertSelective(ErrorCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    ErrorCode selectOneByExample(ErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    ErrorCode selectOneByExampleSelective(@Param("example") ErrorCodeExample example, @Param("selective") ErrorCode.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    List<ErrorCode> selectByExampleSelective(@Param("example") ErrorCodeExample example, @Param("selective") ErrorCode.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    List<ErrorCode> selectByExample(ErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    ErrorCode selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ErrorCode.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    ErrorCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    ErrorCode selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ErrorCode record, @Param("example") ErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ErrorCode record, @Param("example") ErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ErrorCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ErrorCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ErrorCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table error_code
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}